### ISSUE TITLE
this doesn't appear to be working after the last update

### ISSUE THREAD

**Issue by ewatkinsATzvelo** [gabriel-munteanu/SMPlugins#1]
please confirm that the signatures are up to date.. Is there a way to generate these on our own?

**Comment by gabriel-munteanu** [comment]
No, the signatures are not up to date. Right now I don't have time to do this.
I don't know a way to generate them. I use IDA disassembler to search for the signatures in windows and linux binaries.

**Comment by ewatkinsATzvelo** [comment]
Hey, I have the IDA disassembler too. Would you be willing to post a guide on how to do this so I can make this work going forward?

**Comment by gabriel-munteanu** [comment]
I will take time to post a short tutorial about how to do this.

**Comment by ewatkinsATzvelo** [comment]
That would be so awesome. I've read the documentation here: https://wiki.alliedmods.net/Signature_Scanning 

I'm just not quite clear what I need to be looking for. The signature file indicates that there is a text search for " mvm assigned %s to defending team (%d more slots)" and the new text in the game is "MVM assigned %s to defending team (%d more slots remaining after us)"  I'm thinking that the text changed and perhaps offsets for this have changed after the last patch? I'm just working on linux here, not windows, but I do have IDA for other reasons. If the process for linux is easier, I'm all for just getting the downlow on that process.  Any light you can shed on this process is appreciated, I feel like I'm really close.

**Comment by gabriel-munteanu** [comment]
Sorry for not answering for sooooo long. I didn't saw the message. I created a video to explain how to do the update: https://youtu.be/gkh78XN0qWA .
