### ISSUE TITLE
It works on windows but not on linux

### ISSUE THREAD

**Issue by tmvkrpxl0** [gabriel-munteanu/SMPlugins#2]
When the plugins loads, it won't load and prints this
```
L 09/09/2020 - 12:06:39: [SM] Exception reported: Failed to get valid patch value for PreClientUpdate
L 09/09/2020 - 12:06:39: [SM] Blaming: tf2mvm10plr.smx
L 09/09/2020 - 12:06:39: [SM] Call stack trace:
L 09/09/2020 - 12:06:39: [SM]   [0] SetFailState
L 09/09/2020 - 12:06:39: [SM]   [1] Line 29, tf2mvm10plr.sp::OnPluginStart
```
However, it works on windows

**Comment by gabriel-munteanu** [comment]
Yeah, I know this. It's in this state for the last 2 years and half. The signatures for linux need to be updated. I am quite busy right now so I can't promise something.
I will do my best to update those soon and make a video tutorial so anyone can do the update later.

**Comment by tmvkrpxl0** [comment]
Thank you, i'll give you star

**Comment by gabriel-munteanu** [comment]
Can you try this game file? I don't have TF2 installed but I downloaded the server_srv.so binary
[tf2mvm10plr.games.txt](https://github.com/gabriel-munteanu/SMPlugins/files/5207642/tf2mvm10plr.games.txt)

**Comment by tmvkrpxl0** [comment]
Now it works on both linux and windows, Thanks!

**Comment by gabriel-munteanu** [comment]
I am glad it works!
I will create a video this days to explain how I updated the signatures and the offsets.
